### ISSUE TITLE
Lack of Explicit Fortran Module Dependencies Causes Race Condition

### ISSUE THREAD

**Issue by rspavel** [geodynamics/sw4lite#2]
While making an initial spackage (https://github.com/LLNL/spack/pull/5917) I ran into some issues while building the fortran versions in that files would try to be compiled before type_defs.f90 had been used to generate a .mod file. It happened maybe one in every ten times (and I have not been able to reproduce it in just a terminal with make -j), but I disabled the fortran version and only built the ckernels as a result.

I am not an expert on fortran but a quick googling makes it seem like this may be a common issue due to Make not having knowledge of these dependencies.

**Comment by andersp** [comment]
I added a makefile rule to build the .mod file before it is needed for compiling other Fortran files. Try it and let me know if my fix solved your problem.
