### ISSUE TITLE
ERROR: developer option corder, must be zero when fortran routines are used

### ISSUE THREAD

**Issue by zinechant** [geodynamics/sw4lite#8]
Hi,
I am new to this proxy app.
I built it according to the readme and tried to run it with:
```
mpirun -n 4 ./sw4lite ../tests/pointsource/pointsource.in
```
It would say:
```
ERROR: developer option corder, must be zero when fortran routines are use
```
I modified the content of `tests/pointsource/pointsource.in` to make `corder=0` and it will give the same output as the readme:
```
...
Errors at time 0.6 Linf = 0.569416 L2 = 0.0245361 norm of solution = 3.7439
```
Am I doing this right? What is corder?

Thanks in advance.

Regards,
Chen

**Comment by andersp** [comment]
The corder=1 option changes the index ordering in the multi-dimensional arrays inside sw4lite. To use the corder option you must build sw4lite with C-support. You do this with 'make sw4lite ckernel=yes'. By default, sw4lite is built with Fortran kernels that don't support changing the index ordering.

**Comment by zinechant** [comment]
Thanks a lot for the reply.
I am going to close this issue.
